DROP TABLE ROOM_LOC;
DROP TABLE COMMENTS;
DROP TABLE TICKET_PROP;
DROP TABLE USER_T;
DROP TABLE DEPARTMENT;
DROP TABLE SECURITY_QUESTION;
DROP TABLE TASK;

CREATE TABLE ROOM_LOC(
  ROOM_NO VARCHAR2(5)
    CONSTRAINT ROOM_LOC_ROOM_NO_NN NOT NULL
    CONSTRAINT ROOM_LOC_PK PRIMARY KEY
);

CREATE TABLE DEPARTMENT(
  DEP_ID NUMBER(2)
    CONSTRAINT DEPARTMENT_DEP_ID_NN NOT NULL
    CONSTRAINT DEPARTMENT_DEP_ID_PK PRIMARY KEY,
  DEP_NAME VARCHAR2(25)
    CONSTRAINT DEPARTMENT_DEP_NAME_NN NOT NULL
);

CREATE TABLE USER_T(
  U_ID NUMBER(9)
    CONSTRAINT USER_T_U_ID_NN NOT NULL
    CONSTRAINT USER_T_PK PRIMARY KEY,
	FIRSTNAME VARCHAR2(80)
    CONSTRAINT USER_T_FIRSTNAME_NN NOT NULL,
  LASTNAME VARCHAR2(80),
  UNAME VARCHAR2(20)
    CONSTRAINT USER_T_UNAME_NN NOT NULL UNIQUE,
  U_PASSWORD VARCHAR2(16),
  F_ID VARCHAR2(3000),
  EMAIL VARCHAR2(70)
    CONSTRAINT USER_T_EMAIL_NN NOT NULL, 
  PHONE NUMBER(14),
  DEP_ID NUMBER(2)
    CONSTRAINT USER_T_DEP_ID REFERENCES DEPARTMENT (DEP_ID)ON DELETE CASCADE,
  U_STATUS VARCHAR2(8)
    CONSTRAINT USER_T_U_STATUS_NN NOT NULL,
  A1 VARCHAR2(50) NOT NULL,
  A2 VARCHAR2(50) NOT NULL
);

CREATE TABLE TICKET_PROP(
  TICKET_ID NUMBER(3)  
    CONSTRAINT TICKET_PROP_PK PRIMARY KEY
    CONSTRAINT TICKET_PROP_NN NOT NULL,
  STATUS VARCHAR2(15)
    CONSTRAINT TICKET_PROP_STATUS_NN NOT NULL,
  SEVERITY VARCHAR2(15),
  SUBJECT VARCHAR2(100)
    CONSTRAINT TICKET_PROP_SUBJECT_NN NOT NULL,
  ROOM_NO VARCHAR2(5)
    CONSTRAINT TICKET_PROP_ROOM_NO_NN NOT NULL
    CONSTRAINT TICKET_PROP_ROOM_NO REFERENCES ROOM_LOC (ROOM_NO)ON DELETE CASCADE
);
CREATE TABLE COMMENTS(
  TICKET_ID NUMBER(3)
    CONSTRAINT COMMENT_NN NOT NULL
    CONSTRAINT COMMENT_TICKET_ID REFERENCES TICKET_PROP(TICKET_ID) ON DELETE CASCADE,
  TIME_STAMP TIMESTAMP
    CONSTRAINT COMMENTS_TIME_STAMP_NN NOT NULL,
  DESCRIPTION VARCHAR2(500),
  UNAME VARCHAR2(20)
    CONSTRAINT COMMENTS_UNAME_NN NOT NULL
    CONSTRAINT COMMENT_UNAME REFERENCES USER_T(UNAME) ON DELETE CASCADE,
  CONSTRAINT COMMENTS_PK PRIMARY KEY (TICKET_ID, TIME_STAMP)
);

CREATE TABLE SECURITY_QUESTION(
  Q1 VARCHAR2(100)
     CONSTRAINT SECURITY_QUESTION_Q1_NN NOT NULL,
  Q2 VARCHAR2(100)
     CONSTRAINT SECURITY_QUESTION_Q2_NN NOT NULL
);

CREATE TABLE TASK(
  TASK_ID NUMBER
    CONSTRAINT TASK_TASK_ID_PK PRIMARY KEY
    CONSTRAINT TASK_TASK_ID_NN NOT NULL,
  TIME_ID TIMESTAMP
    CONSTRAINT TASK_TIME_ID_NN NOT NULL,
  UASSIGN_BY VARCHAR2(20)
    CONSTRAINT TASK_UASSIGN_BY_NN NOT NULL
    CONSTRAINT TASK_UASSIGN_BY REFERENCES USER_T(UNAME) ON DELETE CASCADE,
   UASSIGN_TO VARCHAR2(20)
    CONSTRAINT TASK_UASSIGN_TO_NN NOT NULL
    CONSTRAINT TASK_UASSIGN_TO REFERENCES USER_T(UNAME) ON DELETE CASCADE,
  DESCRIBE VARCHAR2(500)
    CONSTRAINT TASK_DESCRIBE_NN NOT NULL,
  STAT VARCHAR2(500) 
    CONSTRAINT TASK_STAT_NN NOT NULL
);

INSERT INTO ROOM_LOC (ROOM_NO) VALUES ('A1200');
INSERT INTO ROOM_LOC (ROOM_NO) VALUES ('A1225');
INSERT INTO ROOM_LOC (ROOM_NO) VALUES ('A1250');
INSERT INTO ROOM_LOC (ROOM_NO) VALUES ('A1275');

INSERT INTO DEPARTMENT (DEP_ID, DEP_NAME) VALUES (10, 'TIER 2 TECH');
INSERT INTO DEPARTMENT (DEP_ID, DEP_NAME) VALUES (20, 'NETWORKING');
INSERT INTO DEPARTMENT (DEP_ID, DEP_NAME) VALUES (30, 'TIER 1 TECH');

INSERT INTO USER_T (U_ID, FIRSTNAME, LASTNAME, UNAME, U_PASSWORD, F_ID, EMAIL, PHONE, DEP_ID, U_STATUS) VALUES (100120121, 'VANSH', 'PATEL', 'VP367', 'Vjp@2000', '', 'VANSHDEVPATEL2000@GMAIL.COM', 3430125234, NULL, 'CLIENT');--Vjp@2000
INSERT INTO USER_T (U_ID, FIRSTNAME, LASTNAME, UNAME, U_PASSWORD, F_ID, EMAIL, PHONE, DEP_ID, U_STATUS) VALUES (100120122, 'HET', 'PATEL', 'HP165', 'Hbp@1999', '', 'HETS1699@GMAIL.COM', 3430145434, NULL, 'CLIENT'); --Hbp@1999
INSERT INTO USER_T (U_ID, FIRSTNAME, LASTNAME, UNAME, U_PASSWORD, F_ID, EMAIL, PHONE, DEP_ID, U_STATUS) VALUES (100120123, 'BENJAMIN', 'SHEFLER', 'BS264', 'Tpj@2020', '', 'BENJAMIN.SHEFLER@SENECACOLLEGE.CA', 3430165946, NULL, 'CLIENT');--Tpj@2020
INSERT INTO USER_T (U_ID, FIRSTNAME, LASTNAME, UNAME, U_PASSWORD, F_ID, EMAIL, PHONE, DEP_ID, U_STATUS) VALUES (155121070, 'PRATEEK', 'SINGH', 'PSINGH02', 'Prs@655', '', 'PRATEEK.SINGH110@GMAIL.COM', 3431266447, 10, 'EMPLOYEE');--Prs@655
INSERT INTO USER_T (U_ID, FIRSTNAME, LASTNAME, UNAME, U_PASSWORD, F_ID, EMAIL, PHONE, DEP_ID, U_STATUS) VALUES (155121071, 'JINAL', 'PATEL', 'JPATEL07', 'Jvp@1999', '', 'JINAL.V.PATEL07@GMAIL.COM', 3431246405, 10, 'EMPLOYEE');--Jvp@1999
INSERT INTO USER_T (U_ID, FIRSTNAME, LASTNAME, UNAME, U_PASSWORD, F_ID, EMAIL, PHONE, DEP_ID, U_STATUS) VALUES (155121072, 'KAVYA', 'PATEL', 'KPATEL12', 'Knp@1508', '', 'KAVYANPATEL07@GMAIL.COM', 3431276847, 20, 'EMPLOYEE');--Knp@1508

UPDATE USER_T SET A1='PATEL', A2='SARDA' WHERE UNAME ='VP367';
UPDATE USER_T SET A1='KUMARI', A2='SHILPA' WHERE UNAME ='HP165';
UPDATE USER_T SET A1='QUEEN', A2='KENY' WHERE UNAME ='BS264';
UPDATE USER_T SET A1='SHAH', A2='KOKILA' WHERE UNAME ='PSINGH02';
UPDATE USER_T SET A1='PANDYA', A2='SITA' WHERE UNAME ='JPATEL07';
UPDATE USER_T SET A1='DAVE', A2='KANTA' WHERE UNAME ='KPATEL12';

INSERT INTO SECURITY_QUESTION (Q1, Q2) VALUES ('What is your mothers maiden name?', 'What is your paternal grandmothers name?'); 

DROP SEQUENCE TASK_ID_SEQUENCE;
DROP SEQUENCE TICKET_ID_SEQUENCE;

CREATE SEQUENCE TICKET_ID_SEQUENCE
	INCREMENT BY 1
	START WITH 100;

CREATE SEQUENCE TASK_ID_SEQUENCE
	INCREMENT BY 1
	START WITH 1;
COMMIT;
